name : cpprun
on:
  push:
    branches:
      -main
    pull_request:
      branches:
        -main
jobs:
  build:
    runs-on:ubuntu-latest
    steps:
      - name:Checkout code
        uses:actions/checkout@v2
      - name:install g++
        run:sudo apt install g++
      - name:compile
        run:g++ -g main.cpp -o main -std=c++17
      - name:run
        run:./main
